version: "3.8"

services:
  demo:
    image: nginxdemos/hello:0.4
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - traefik.http.middlewares.compress.compress=true
      - traefik.enable=true
      - traefik.http.routers.demo.rule=Host(`test.local`)
      - traefik.http.routers.demo.entrypoints=websecure
      - traefik.http.routers.demo.middlewares=compress