version: "3.8"

services:
  demo:
    image: nginxdemos/hello:0.4
    restart: unless-stopped
    networks:
      - traefik_web
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.compress.compress=true
      - traefik.http.routers.demo.rule=Host(`test.de`)
      - traefik.http.routers.demo.middlewares=compress

networks:
  traefik_web:
    external: true