version: '3.8'
include:
  - path: container/test.yml
#  - path: container/mastodon.yml
#  - path: services/rustdesk.yml # check if yml is correct
# bookstack
# collabora
# commento oder Ähnliches
# ggf. leantime

services:
  traefik:
      image: traefik:v3.0
      restart: unless-stopped
      ports:
        - "443:443/tcp"
        - "443:443/udp"
        - "80:80"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./letsencrypt:/letsencrypt
        - ./traefik.yml:/traefik.yml
      networks:
        - traefik
      command:
        - "--providers.file.filename=/traefik.yml"

volumes:
  acme-data:

networks:
  traefik:
    name: traefik_web
